lfm2_vl_src = [
    meson.current_source_dir() / 'lfm2_vl_embedding_merge.cpp',
    meson.current_source_dir() / 'lfm2_vl_for_conditional_generation.cpp',
    meson.current_source_dir() / 'lfm2_vl_prefill.cpp',
]

lfm2_vl_inc = include_directories('.')

causallm_src += lfm2_vl_src
causallm_inc += lfm2_vl_inc
